### ISSUE TITLE
What Are the Results on AntPush and AntFall?

### ISSUE THREAD

**Issue by peasant98** [trzhang0116/HRAC#1]
Hi, I was curious as to what the results of HRAC were on the Mujoco-based AntPush and AntFall environments. 

They were both included in the original HIRO and near-optimal representation HIRO, so I'd like to know how they fared here.

**Comment by trzhang0116** [comment]
Hi, we have not tried AntPush or AntFall yet due to some time constraints, but we are also willing to check the performance of HRAC on these two challenging tasks. We may do so in the future, and the results will be updated here once we have finished these experiments.

**Comment by peasant98** [comment]
Cool,  I might run them and see, they'll probably be better than HIRO.
