### ISSUE TITLE
code for Key-Chest

### ISSUE THREAD

**Issue by rainandwind1** [trzhang0116/HRAC#2]
Hello, bro, i wanna know why there is no Key-Chest experiments in the code, i am interested in it.

**Comment by trzhang0116** [comment]
Hello, we will soon update the code as well as adding the code for Maze and Key-Chest environments in June, after the deadline of NeurIPS 2021.

**Comment by rainandwind1** [comment]
Ok, understand, thanks bro.

**Comment by peasant98** [comment]
This is tangential to this issue, but @trzhang0116, will your NeurIPS submission be available soon? Thanks!

**Comment by trzhang0116** [comment]
> 
> 
> This is tangential to this issue, but @trzhang0116, will your NeurIPS submission be available soon? Thanks!

Sorry but I'm not so sure. Maybe we will upload a version of the paper to arXiv if it is accepted. Also I have to note that the topic of our new submission is not relevant to this repo and HRL. Hope that this has not caused some misunderstanding.

**Comment by peasant98** [comment]
I see, thanks for the update!

**Comment by trzhang0116** [comment]
> 
> 
> Hello, bro, i wanna know why there is no Key-Chest experiments in the code, i am interested in it.

Hi @rainandwind1, we have uploaded the code for experiments on Maze and Key-Chest tasks. Please see the `discrete/` folder.

**Comment by rainandwind1** [comment]
> > Hello, bro, i wanna know why there is no Key-Chest experiments in the code, i am interested in it.
> 
> Hi @rainandwind1, we have uploaded the code for experiments on Maze and Key-Chest tasks. Please see the `discrete/` folder.
Ok, thanks bro!
